### ISSUE TITLE
LFQ experiment lost technical repetitions in feature.parquet

### ISSUE THREAD

**Issue by WangHong007** [bigbio/quantms.io#41]
> run: The column stores IDs of mass spectrometry runs for LFQ experiments e.g. 1. For TMT/iTRAQ experiments, it is a identifier of mixture combined with technical replicate and fractions {mixture}_{technical_replicate}_{fraction} e.g. 1_2_3 -> string

@ypriverol Compared to the TMT experiment, the LFQ experiment lost information about the technical repetitions, and its `run` column was just a simple count against mass spectrum files. However, this would seem to implement definitions such as `{technical_replicate}_{fraction}` when merging SDRF.

**Comment by ypriverol** [comment]
This has been fixed.
