### ISSUE TITLE
CamelCase vs snake_case

### ISSUE THREAD

**Issue by ypriverol** [bigbio/quantms.io#54]
In the first iteration of the format we used snake_case for most of the columns. During my recent PR #50 I have been working to remove `.` from some of the names and use CamelCase for the columns because of two reasons: 
- It is PySpark parquet common. 
- Most proteomics formats using `CamelCase` style include DIA-NN, MQ, or Spectronaut. Apart from mzparquet from @lazear ;) 
 
However, I would like to have a vote on this for the first release of format 1.0. The main decision should be based on compatibility with other technologies and readability.  If you don't have an opinion and you don't want to comment just vote for the best option from your side: (👍 CamelScase), (🚀 snake_case). But please, feel free to comment on the issue. @zprobot @timosachsenberg @jpfeuffer @wfondrie @lazear @daichengxin @mobiusklein

**Comment by daichengxin** [comment]
SQL syntax is case insensitive when we using SQL syntax. Like 
```
g = duckdb.sql("""
       SELECT *
        FROM read_parquet('PXD002854-80934754-57c1-47e2-9951-787ef703a484.psm.parquet')
        WHERE retention_time > 20;
        """)
```
equivalence to:
```
g = duckdb.sql("""
       SELECT *
        FROM read_parquet('D:/PXD019909.1_USI/single_run/PXD002854-80934754-57c1-47e2-9951-787ef703a484.psm.parquet')
        WHERE Retention_Time > 20;
        """)
```
In this case, I favor lowercase for better compatibility.

**Comment by timosachsenberg** [comment]
I don't have a strong opinion here. Slightly lean to snake here

**Comment by ypriverol** [comment]
@timosachsenberg Vote.

**Comment by ypriverol** [comment]
Looks like snake_case is the best option. Linking the issue to the PR #50
