### ISSUE TITLE
All the packages or libraries that need to be installed before using quantms.

### ISSUE THREAD

**Issue by hjn0415a** [bigbio/quantms.io#69]
I'd like to ask about all the packages or libraries that need to be installed before using quantms.
or Is there a Docker image available to easily use quantms by any chance?

**Comment by jpfeuffer** [comment]
Hi,
Thanks for your interest in quantms.
First of all, this is the repository for the in and output format only.
For the nextflow pipeline please see https://github.com/bigbio/quantms with all it's documentation.
Short answer: You only need nextflow (which needs Java) and a container software like docker.

**Comment by hjn0415a** [comment]
@jpfeuffer 

Hi, Thanks for your answer. 

When I execute the code below,
The error message shows up.

nextflow run nf-core/quantms -r 1.2.0 -profile test --outdir <OUTDIR>

![Screenshot 2024-10-10 122848](https://github.com/user-attachments/assets/3594c080-6415-4271-8115-851f288b2be6)

After installing pandas, the error message keeps showing up. It seems I need a few more things to install.

**Comment by jpfeuffer** [comment]
If you are not using a profile (docker, conda, singularity, ..) with `-profile XYZ` you will need to have everything in your current environment.

Please see the documentation:
https://docs.quantms.org/en/latest/usage.html

**Comment by JKVISION1101** [comment]
@jpfeuffer 

Thanks for your reply.

Our team (@hjn0415a ) isn't familiar with this program(nextflow,docker...) and is struggling with it....

We downloaded docker also downloaded nextflow.

and we followed the documentation which you mentioned.

we typed `nextflow run bigbio/quantms -r dev -profile test_lfq,docker`

and there is error that there is no sdfr file. 

![image](https://github.com/user-attachments/assets/1c4abefd-6142-4de6-ad9a-a416512c9890)



Also,I think we need to learn how to use quantms in the nexflow...

If you have any more detailed documentation or manul, it is very useful for us.

Thank you.

**Comment by jpfeuffer** [comment]
It says docker not found. So docker is not installed correctly.

If you get sdrf not found you were probably not using a test profile. In this case, of course input parameters are necessary.

https://github.com/bigbio/quantms/tree/dev?tab=readme-ov-file#usage

**Comment by hjn0415a** [comment]
Hi, 

nextflow run nf-core/quantms -r 1.2.0 -profile docker --input 'https://raw.githubusercontent.com/nf-core/test-datasets/quantms/testdata-aws/lfq_full/PXD001819.sdrf.tsv' --database 'https://raw.githubusercontent.com/nf-core/test-datasets/quantms/testdata-aws/lfq_full/yeast_2021_04_reviewed.fasta' --outdir ~
 
After running the code above, I got this error message.

ERROR ~ ERROR: Please check input file -> File Uri does not exist!
http://ftp.ebi.ac.uk/pride-archive/2015/12/PXD001819/UPS1_50amol_R1.raw

Can I get another test input and database URI?

**Comment by jpfeuffer** [comment]
Interesting, the file URI does exist for me. Do you have Internet access on the nodes? Can you check if you can download the file manually from wherever the pipeline is running?

**Comment by hjn0415a** [comment]
It worked when I did it over. but I got this error message again.

![error1](https://github.com/user-attachments/assets/afd516b8-9378-40be-9f0c-71c0956fa18e)
![error2](https://github.com/user-attachments/assets/fe909ebb-476c-4cec-834a-eb75a3c2cdd8)

**Comment by jpfeuffer** [comment]
Which operating system is this?

**Comment by hjn0415a** [comment]
It's Ubuntu 20.04.6 LTS.

**Comment by hjn0415a** [comment]
when I run the command 
'nextflow run bigbio/quantms -r 1.3.0 -profile test --outdir /mnt/c/Users/admin',

I got this error message. 
![msgf](https://github.com/user-attachments/assets/84d1c287-d6e8-418b-844a-58beffb58bc3)

and when I run the command
'nextflow run bigbio/quantms -r 1.3.0 -profile docker --input 'https://raw.githubusercontent.com/nf-core/test-datasets/quantms/testdata-aws/lfq_full/PXD001819.sdrf.tsv' --database 'https://raw.githubusercontent.com/nf-core/test-datasets/quantms/testdata-aws/lfq_full/yeast_2021_04_reviewed.fasta' --outdir /mnt/c/Users/admin'

I got this error message.
![빅바이오1](https://github.com/user-attachments/assets/18d8e3af-8e2b-43bb-b749-d51f71f57c3b)
![빅바이오2](https://github.com/user-attachments/assets/bd434942-cd56-446a-9760-7e38a9de1ff3)

**Comment by jpfeuffer** [comment]
`/mnt/c/Users/admin` this is not Ubuntu! This is Windows subsystem for Linux. Please see https://github.com/bigbio/quantms/issues/270

Unfortunately we cannot support WSL because none of the developers have a Windows PC.
