### ISSUE TITLE
scan number or scan

### ISSUE THREAD

**Issue by ypriverol** [bigbio/quantms.io#74]
The current definition of the `scan` (point to the MS/MS) is the following: 

https://github.com/bigbio/quantms.io/blob/dev/docs/README.adoc#scan-number. 

This is similar to the USI definition. However, the USI included a prefix called `nativeId`, `scan`, or `index`. However, big datasets can introduce a lot of unnecessary text that makes the big files even bigger. 

We will use as the name of the column the generic term `scan` wihch could be a `nativeId`, `scan` or `index`. We will recommend in each section to add extra metadata at the file level of the type of scan: `nativeId`, `scan` or `index`. This will be only one string for the entire definition.

**Comment by timosachsenberg** [comment]
I am not sure, but I thought I came across files where one number is not sufficient?

**Comment by ypriverol** [comment]
Yes, in the specification that is explained now, is called nativeId and can be written separated by `,`
