### ISSUE TITLE
PSM file metadata section. 

### ISSUE THREAD

**Issue by ypriverol** [bigbio/quantms.io#77]
@timosachsenberg make a good point that we should have some metadata at the file level. Parquet allows that by using file metadata. In my last commit, I added a definition for file metadata at PSM level (https://github.com/bigbio/quantms.io/blob/dev/docs/README.adoc#1213-psm-file-metadata). 

Would be good to have your input here @timosachsenberg @zprobot. Im adding some of the metadata terms that are needed at PSM level, but if you have ideas about additional terms that we can add at file level let me know in this issue.

**Comment by timosachsenberg** [comment]
one minor thing: what if the scan_format differs between files of a larger experiment?

**Comment by jpfeuffer** [comment]
True but then it would be from different instruments and the results not really comparable anyway?

If you want to support that you could add a scan_format column. Should not eat much space with a run length encoded dictionary.

**Comment by ypriverol** [comment]
Agree with @jpfeuffer. Another possibility is to be able to write for merged files as: 

```
scan:5
nativeId: 1,3,5,6
.
.
.
```

Which means that scan_format prefix each scan value. I can add a section to that in the document.

**Comment by timosachsenberg** [comment]
I think it is just a design decision. I am happy with having split files for different instruments

**Comment by ypriverol** [comment]
@timosachsenberg @jpfeuffer check how I wrote it here https://github.com/bigbio/quantms.io/blob/dev/docs/README.adoc#33-scan-scan-number
