### ISSUE TITLE
inference representation at psm level. 

### ISSUE THREAD

**Issue by ypriverol** [bigbio/quantms.io#78]
In the current mztab, the protein inference is removed. I think it is a good idea to put all the proteins in the protein group at the psm level. 

The current proposal at PSM level stores the following information: 

-`pg_accessions`
- `pg_positions`
- `unique`
- `pg_global_qvalue`
- `gg_accessions`
- `gg_names`

I added a comment in the specification like: 

```
 Protein inference SHOULD NOT be included in the psm view, as it is not the main purpose of the psm view. Then, is
 RECOMMENDED that all proteins mapping to the peptide in the psm view are included in the `pg_accessions`,
 `pg_positions`, `gg_accessions` and `gg_names` fields. For protein inference please look into the feature view
 (<<feature>>) and protein group (<<pg>>).
```

@timosachsenberg @jpfeuffer @zprobot

**Comment by ypriverol** [comment]
What do you mean by indirection? 

- In the current mzTab we removed all the inference information. I don't like it but is the way to implement it. This causes a lot of issues because protein accessions between features and psms do not match. However, it does facilitate knowing all the mapping between peptides + proteins in the fasta.  

More importantly, you @jpfeuffer are the one who knows more about this. Can you refine the psm, feature and pg (protein groups) definitions. Helps us to implement the protein group in quantms.io. How do you think we should handle psms in the protein group?

**Comment by jpfeuffer** [comment]
I dont think you need ANY protein information at the psm level because you can go to the feature level and lookup the protein information there (protein group information or not, does not matter).

**Comment by ypriverol** [comment]
The idea of having protein information at PSM level served mainly for filtering purposes. For example: 

- Get all PSMS for protein A. 
- Does protein A have more PSMs that protein B. 

You can respond to that easily without merging files etc and doing joins across files. I agree that should be optional but if available, adding all the proteins where the peptide maps is not a bad idea. Especially, because we may use the format in some use cases where no inference and no quant is performed. Phospho proteomics, where you just one phospho site by proteins, then we may have only protein group and psm views.

**Comment by ypriverol** [comment]
The question here at PSM level is @timosachsenberg @jpfeuffer @zprobot: 
- (A) no protein information. 
- (B) do not inference information, all proteins that the psm map to include it (mztab, current quantms). 
- (C) use protein groups, the same approach as MQ, FragPipe.

**Comment by jpfeuffer** [comment]
I do not like c) at all since this gives false impressions about the certainty of the association of this PSM to a protein group.

Regarding a)
You could provide a few lines helper function in the quantms.io package to query that information across files.
I think even phosphoproteomics should/could have a peptide/feature table. Potentially without quantities.


But I am fine with b), too.

**Comment by timosachsenberg** [comment]
> I do not like c) at all since this gives false impressions about the certainty of the association of this PSM to a protein group.
> People will not be able to do their own inference anymore without doing a peptide indexing step in the original fasta/ protein sequences.

I can't really say because I think this depends on what the purpose of the format should ultimately be and what we denormalize for faster look-ups. If it is a final result, then using the protein group is imho fine (MQ and MSFragger seem to be fine with that). If we need to do inference again, then one needs to index again or trace back the sequence through peptides to proteins etc.? But I wonder if this could also impact other entries (e.g., site localization based on several replicates etc.). "Inference" of modifications in open modification searches based on many runs and observed mass+retention time shifts etc.

@jpfeuffer how fast would a) be for many files in your view?

**Comment by ypriverol** [comment]
Here the definition of mztab for psms: 

>The protein's accession to the corresponding peptide sequence (coming from the PSM) is associated with. In case no protein section is present in the file or the peptide was not assigned to a protein the field should be filled with “null”. If the PSM can be assigned to more than one protein, the same PSM should be represented on multiple rows with the same unique identifier.

**Comment by ypriverol** [comment]
Another option @jpfeuffer @timosachsenberg : 

| Field Name              | Description                                                        | Data Type          | MaxQuant        | FragPipe       | mzTab                          |
|-------------------------|--------------------------------------------------------------------|--------------------|-----------------|----------------|---------------------------------|
| **pg_accessions**        | Protein group accessions of all the proteins that the peptide maps to | array[string], null | Protein.Ids     | Proteins       | accession                       |
| **unique**               | Unique peptide indicator, 1 if the peptide maps to a single protein, otherwise 0 | int32, null        | Is Unique       | Unique         | unique                          |
| **protein_global_qvalue**| Global q-value of the protein group at the experiment level        | float32, null       | Global.PG.Q.Value | best_search_engine_score | best_search_engine_score   |
| **gg_accessions**        | Gene group accessions, as a string array                           | array[string], null | -               | -              | -                               |
| **gg_names**             | Gene group names, as a string array                               | array[string], null | -               | -              | -                               |
| **mp_accessions**        | Protein accessions of all the proteins that the peptide maps to    | array[string], null | Protein.Ids     | Proteins       | accession                       |
| **mg_accessions**        | Gene accessions of all the proteins that the peptide maps to       | array[string], null | -               | -              | -                               |
| **mg_names**             | Gene names of all the proteins that the peptide maps to            | array[string], null | -               | -              | -                               |

This one is a combination of B and C.

**Comment by ypriverol** [comment]
After some discussion, I propose to remove all the inference from psm tables. Resulting on this proposal: 

| Field Name              | Description                                                        | Data Type          | MaxQuant        | FragPipe       | mzTab                          |
|-------------------------|--------------------------------------------------------------------|--------------------|-----------------|----------------|---------------------------------|
| **unique** | Unique peptide indicator, 1 if the peptide maps to a single protein, otherwise 0 | int32, null | Is Unique | Unique         | unique |
| **pglobal_qvalue**| Global q-value at protein  + experiment level | float32, null  | Global.PG.Q.Value | - | - |
| **mp_accessions**        | Protein accessions of all the proteins that the peptide maps to    | array[string], null | Protein.Ids     | Proteins       | accession |


> Protein inference SHOULD NOT be included in the psm view, as it is not the main purpose of the psm view. However, for some use cases like peptide filtering, search, etc, maybe interesting to have access to all the psms for a given protein accession, you can include that in the `mp_accessions`: mapped protein accessions. For protein inference please look into the feature view (<<feature>>) and protein group (<<pg>>).
